name: CI

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test" --health-interval 10s --health-timeout 5s --health-retries 5

      keycloak:
        image: ghcr.io/sofiaaristizabal/mykeycloak:latest
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: "true"
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v4 #clona el repositorio en el runner (la maquina que ejecuta el job en github actions, estamos usando un runner que provee github, pero tambien se puede hacer self-host de runners

      - name: Set up JDK 25
        uses: actions/setup-java@v4  #installa java en el runner, configura el JDK en la version correcta y el maven cache
        with:
          distribution: temurin
          java-version: '25'
          cache: maven

      - name: Wait for services
        run: |
          docker ps
          until docker exec $(docker ps -qf "ancestor=postgres:15") pg_isready -U test; do
            echo "Waiting for postgres..."
            sleep 2
          done
      - name: Wait for keycloak
        run: |
          echo "Waiting for Keycloak..."
          until curl -sf http://localhost:8080/health/ready | grep -q UP; do
            echo "  not ready yet..."
            sleep 5
          done
          echo "Keycloak is ready!"

      - name: Build & run tests
        run: mvn -B -e clean verify -Dspring.profiles.active=test #aqui generamos el .jar

      - name: Print surefire report on failure
        if: failure()
        run: cat target/surefire-reports/*.txt